# my.age = 31 
# my.name = bgbbfgbbfbf
# my.env = dev 


my:
  age: 31 
  name: changed
  env: dev 

oauth:
  jwt:
    secret:
      6B64DCA4E72F58EDIKU9AAB215FE7ASDACZWQEQWEQEQWE
  oauth2:
      authorizedRedirectUri: http://localhost:8080/oauth2/redirect
